# Generated by Django 4.2.10 on 2024-03-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('City', models.CharField(blank=True, max_length=150, null=True)),
                ('State', models.CharField(blank=True, max_length=10, null=True)),
                ('Zip', models.IntegerField(blank=True, null=True)),
                ('Bank', models.CharField(blank=True, max_length=150, null=True)),
                ('BankState', models.CharField(blank=True, max_length=10, null=True)),
                ('NAICS', models.IntegerField(blank=True, null=True)),
                ('ApprovalDate', models.DateField(blank=True, null=True)),
                ('ApprovalFY', models.DateField(blank=True, null=True)),
                ('Term', models.IntegerField(blank=True, null=True)),
                ('NoEmp', models.IntegerField(blank=True, null=True)),
                ('NewExist', models.IntegerField(blank=True, null=True)),
                ('CreateJob', models.IntegerField(blank=True, null=True)),
                ('RetainedJob', models.IntegerField(blank=True, null=True)),
                ('DiffJobs', models.IntegerField(blank=True, null=True)),
                ('FranchiseCode', models.IntegerField(blank=True, null=True)),
                ('UrbanRural', models.IntegerField(blank=True, null=True)),
                ('RevLineCr', models.CharField(blank=True, max_length=1, null=True)),
                ('LowDoc', models.CharField(blank=True, max_length=1, null=True)),
                ('GrAppv', models.FloatField(blank=True, null=True)),
                ('SBA_Appv', models.FloatField(blank=True, null=True)),
                ('MIS_Status', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
