# Generated by Django 4.2.11 on 2024-03-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelapi',
            name='Name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='modelapi',
            name='process_status',
            field=models.IntegerField(blank=True, default='1', null=True),
        ),
    ]
