version: '3.8'
services:
  django_us_sba:
    ports:
      - 8006:8000
    env_file:
      - django_us_sba/.env
    build:
      context: ./django_us_sba/
      dockerfile: Dockerfile
    volumes:
      - ./django_us_sba/:/app/

  postgres_db:
    image: postgres
    restart: always
    env_file:
      - django_us_sba/.env
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      
  api_predict:
    ports:
      - 8001:8001
    build:
      context: ./api_predict/
      dockerfile: Dockerfile

volumes:
  postgres_data: